filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/log/ibm/csm/csm_transaction.log
  tags: ["transaction"]

- type: log 
  enabled: true
  paths:
    - "/var/log/ibm/csm/archive/*.json"
  tags: ["archive"]

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

name: "master"

setup.kibana:
  host: "60.7.4.30:5601"

output.logstash:
  hosts: ["10.7.4.41:10523"]
