#  sudo ansible-playbook -i hosts  <this.yml>

- hosts: server
  tasks:
  - name: Skip any activation if bbserver is running
    command:  /bin/systemctl status bbserver.service 
    register: bbserver_service_result
    ignore_errors: yes

  - debug:
      msg:  bbserver.service is not running
    when: bbserver_service_result.rc != 0

- hosts: compute
  tasks:
  - name: Skip any activation if bbproxy is running
    command:  /bin/systemctl status bbproxy.service 
    register: bbproxy_service_result
    ignore_errors: yes

  - debug:
      msg:  bbproxy.service is not running
    when: bbproxy_service_result.rc != 0

  - name: check export_layout module is loaded
    shell: lsmod |grep export_layout 
    register: export_layout_loaded
    ignore_errors: yes

  - debug:
      msg: export_layout module is NOT loaded
    when:  export_layout_loaded.rc != 0 
   