#  sudo ansible-playbook -i hosts  <this.yml>

- hosts: all
  tasks:
  - name: check all nodes for RPM directory
    command: /usr/bin/file {{RPMDIR}} 
    any_errors_fatal: true

- hosts: launch
  tasks:
  - name: install BB RPMs on launch node
    shell: "yum localinstall -y {{RPMDIR}}/ibm-burstbuffer-*.rpm {{RPMDIR}}/ibm-flightlog-[01]*.rpm"
    args:
      warn: false # set warn=false to prevent warning       

- hosts: server
  tasks:
  - name: Skip any activation if bbserver is running
    command:  /bin/systemctl status bbserver.service 
    register: bbserver_service_result
    ignore_errors: yes

  - name: Installl BB RPMs on ESS
    shell: "yum localinstall -y {{RPMDIR}}/ibm-burstbuffer-[01]*.rpm {{RPMDIR}}/ibm-flightlog-[01]*.rpm"
    args:
      warn: false # set warn=false to prevent warning
    when: bbserver_service_result.rc != 0
    any_errors_fatal: true

  - name: systemctl daemon-reload on ESS
    command: systemctl daemon-reload  

- hosts: compute
  tasks:
  - name: Skip any activation if bbproxy is running
    command:  /bin/systemctl status bbproxy.service 
    register: bbproxy_service_result
    ignore_errors: yes

  - name: install BB RPMs on Compute
    shell: "yum localinstall -y {{RPMDIR}}/ibm-burstbuffer-*.rpm {{RPMDIR}}/ibm-flightlog-[01]*.rpm"
    args:
      warn: false # set warn=false to prevent warning 
    when: bbproxy_service_result.rc != 0

  - name: bb systemctl daemon-reload on compute
    command: systemctl daemon-reload
    when: bbproxy_service_result.rc != 0
    


   