#  sudo ansible-playbook -i hosts  <this.yml>

- hosts: server
  tasks:
  - name: Skip any activation if bbserver is running
    command:  /bin/systemctl status bbserver.service 
    register: bbserver_service_result
    ignore_errors: yes

  - name: Start bbServer
    command: /opt/ibm/bb/scripts/bbactivate --server --metadata=/gpfs/gpfs0/bbmetadata
    when: bbserver_service_result.rc != 0
    any_errors_fatal: true

  - name: Fail if bbserver daemon is not now running
    command:  /bin/systemctl status bbserver.service 
    register: bbserver_service_result
    any_errors_fatal: true  

- hosts: compute
  tasks:
  - name: Skip any activation if bbproxy is running
    command:  /bin/systemctl status bbproxy.service 
    register: bbproxy_service_result
    ignore_errors: yes

  - name: Start BB on computes
    command: /opt/ibm/bb/scripts/bbactivate --sharednode --csm
    when: bbproxy_service_result.rc != 0

  - name: Check bbproxy is running
    command:  /bin/systemctl status bbproxy.service 
    register: bbproxy_service_result
    any_errors_fatal: true  
  
- hosts: launch
  tasks:
  - name: start Burst Buffer on Launch node 
    command: /opt/ibm/bb/scripts/bbactivate --ln --bscfswork=/u/tgooding/bscfswork --envdir=HOME --lsfdir=/opt/ibm/spectrumcomputing/lsf/10.1/linux3.10-glibc2.17-ppc64le-csm/etc
    any_errors_fatal: true


   