###########################################################
#     bbStop.yml
#
#     Copyright IBM Corporation 2020 All Rights Reserved
#
#     This program is licensed under the terms of the Eclipse Public License
#     v1.0 as published by the Eclipse Foundation and available at
#     http://www.eclipse.org/legal/epl-v10.html
#
#     U.S. Government Users Restricted Rights:  Use, duplication or disclosure
#     restricted by GSA ADP Schedule Contract with IBM Corp.
###########################################################
#  sudo ansible-playbook -i hosts  <this.yml>

- hosts: compute
  tasks:
  - name: bbproxy bbactivate --cn --shutdown
    ignore_errors: yes
    command: /opt/ibm/bb/scripts/bbactivate --cn --shutdown {{BBACTIVATE_PARMS}}

  - name: Handle bbactivate did not do shutdown (bbhealth)
    command: /bin/systemctl stop bbhealth.service 
    ignore_errors: yes  

  - name: Handle bbactivate did not do shutdown (bbproxy)
    command: /bin/systemctl stop bbproxy.service 
    ignore_errors: yes  

- hosts: server
  tasks:
  - name: bbserver bbactivate --server --shutdown
    command: /opt/ibm/bb/scripts/bbactivate --server --shutdown {{BBACTIVATE_PARMS}}
    register: bbserver_shutdown
    ignore_errors: yes

  - name: Handle bbactivate did not shutdown bbserver
    command: /bin/systemctl stop bbserver.service 
    ignore_errors: yes  

 
    

