
- hosts: management launch compute
  tasks:  
  - name: stop CSM master
    command: /bin/systemctl stop csmd-master.service
    ignore_errors: yes
  
  - name: stop CSM aggregator
    command: /bin/systemctl stop csmd-aggregator.service
    

- hosts: launch
  tasks:
  - name: stop csmd-utility
    command: /bin/systemctl stop csmd-utility.service
    ignore_errors: yes
    

- hosts: compute
  tasks:
  - name: stop CSM compute
    command: /bin/systemctl stop csmd-compute.service
    ignore_errors: yes
