
#check to see if hosts are available--fail if not reachable
- hosts: management launch compute
  tasks:
  any_errors_fatal: true 

- hosts: management
  tasks:
  - name: Skip any csmd-master activation if already running
    command:  /bin/systemctl status csmd-master.service 
    register: csmdmaster_service_result
    ignore_errors: yes

  - name: Skip any ccsmd-aggregator activation if already running
    command:  /bin/systemctl status csmd-aggregator.service 
    register: csmdaggregator_service_result
    ignore_errors: yes
    
  - name: start CSM master
    command: /bin/systemctl start csmd-master.service
    when: csmdmaster_service_result.rc != 0
    any_errors_fatal: true
  
  - name: start CSM aggregator
    command: /bin/systemctl start csmd-aggregator.service
    when: csmdaggregator_service_result.rc != 0
    any_errors_fatal: true
    
- hosts: launch
  tasks:
  - name: Skip any csmd-utility activation if already running
    command:  /bin/systemctl status csmd-utility.service 
    register: csmdutility_service_result
    ignore_errors: yes

  - name: start csmd-utility
    command: /bin/systemctl start csmd-utility.service
    when: csmdutility_service_result.rc != 0 
    any_errors_fatal: true

- hosts: compute
  tasks:
  - name: Skip any csmd-compute activation if already running
    command:  /bin/systemctl status csmd-compute.service 
    register: csmdcompute_service_result
    ignore_errors: yes

  - name: start CSM compute
    command: /bin/systemctl start csmd-compute.service
    when: csmdcompute_service_result.rc != 0  
    any_errors_fatal: true