###########################################################
#     mpiInstall.yml
#
#     Copyright IBM Corporation 2020 All Rights Reserved
#
#     This program is licensed under the terms of the Eclipse Public License
#     v1.0 as published by the Eclipse Foundation and available at
#     http://www.eclipse.org/legal/epl-v10.html
#
#     U.S. Government Users Restricted Rights:  Use, duplication or disclosure
#     restricted by GSA ADP Schedule Contract with IBM Corp.
###########################################################
#  sudo ansible-playbook -i hosts  <this.yml>

- hosts: compute launch
  tasks:
  - name: install smpi RPMs
  - shell: yum -y localinstall "{{SMPIRPMDIR}}/ibm_smpi*rpm"
    ignore_errors: yes 

  - name: Accept MPI license
  - shell:  IBM_SPECTRUM_MPI_LICENSE_ACCEPT=yes /opt/ibm/spectrum_mpi/lap_se/bin/accept_spectrum_mpi_license.sh
    ignore_errors: yes   