###########################################################
#     mpiUninstall.yml
#
#     Copyright IBM Corporation 2020 All Rights Reserved
#
#     This program is licensed under the terms of the Eclipse Public License
#     v1.0 as published by the Eclipse Foundation and available at
#     http://www.eclipse.org/legal/epl-v10.html
#
#     U.S. Government Users Restricted Rights:  Use, duplication or disclosure
#     restricted by GSA ADP Schedule Contract with IBM Corp.
###########################################################
#  sudo ansible-playbook -i hosts  <this.yml>

- hosts: compute launch
  tasks:
  - name: uninstall smpi RPMs
  - shell: yum erase -y ibm_smpi_lic_s ibm_smpi_lic_c ibm_smpi ibm_smpi-devel ibm_smpi-jsm ibm_smpi-pami_devel ibm_smpi_gpusupport
    ignore_errors: yes 

