s

- hosts: compute launch
  tasks:
  - name: uninstall smpi RPMs
  - shell: yum erase -y ibm_smpi_lic_s ibm_smpi_lic_c ibm_smpi ibm_smpi-devel ibm_smpi-jsm ibm_smpi-pami_devel ibm_smpi_gpusupport
    ignore_errors: yes 

