#  sudo ansible-playbook -i hosts  <this.yml>

#check to see if all hosts are available--fail if not reachable

- hosts: compute
  serial: 1
  tasks:
  - name: create nodelist
    file:
      dest: /tmp/nodelist
      state: touch
    delegate_to: localhost

  - name: echo hostname
    shell: echo "{{ inventory_hostname }}"
    register: hostnamevar

  - name: build host list
    lineinfile:
      dest: /tmp/nodelist 
      line: "{{hostnamevar.stdout}}"
      insertafter: EOF
    delegate_to: localhost
      
- hosts: launch
  tasks:
  - name: Copy nodelist to launch nodes
    copy:
        src: /tmp/nodelist
        dest: /etc/ibm/nodelist
        owner: root
        group: root
        mode: '0644'
        backup: yes  
    any_errors_fatal: true    
