cluster.name: CLUSTER-NAME
node.name: ${HOSTNAME}
path.data: DATA-PATH
path.logs: LOG-DIR
network.host: BIND-ADDRESS
http.port: 9200
discovery.zen.ping.unicast.hosts: cast.elasticsearch.nodes
discovery.zen.minimum_master_nodes: MIN-NODES
gateway.recover_after_nodes: REC-NODES
xpack.ml.enabled: false
xpack.license.self_generated.type: basic
bootstrap.system_call_filter: false

