###########################################################
#     csmCheck.yml
#
#     Copyright IBM Corporation 2020 All Rights Reserved
#
#     This program is licensed under the terms of the Eclipse Public License
#     v1.0 as published by the Eclipse Foundation and available at
#     http://www.eclipse.org/legal/epl-v10.html
#
#     U.S. Government Users Restricted Rights:  Use, duplication or disclosure
#     restricted by GSA ADP Schedule Contract with IBM Corp.
###########################################################
#  sudo ansible-playbook -i hosts  <this.yml>

- hosts: management launch compute
  tasks:
  any_errors_fatal: true 

- hosts: management
  tasks:
  - name: Skip any csmd-master activation if already running
    command:  /bin/systemctl status csmd-master.service 
    register: csmdmaster_service_result
    ignore_errors: yes

  - name: Skip any csmd-aggregator activation if already running
    command:  /bin/systemctl status csmd-aggregator.service 
    register: csmdaggregator_service_result
    ignore_errors: yes
    
  - debug: 
      msg: csmd-master.service is NOT running
    when: csmdmaster_service_result.rc != 0

  - debug: 
      msg: csmd-aggregator.service is NOT running
    when: csmdaggregator_service_result.rc != 0
    
- hosts: launch
  tasks:
  - name: Skip any csmd-utility activation if already running
    command:  /bin/systemctl status csmd-utility.service 
    register: csmdutility_service_result
    ignore_errors: yes

  - debug: 
      msg: csmd-utility.service is NOT running
    when: csmdutility_service_result.rc != 0 

- hosts: compute
  tasks:
  - name: Skip any csmd-compute activation if already running
    command:  /bin/systemctl status csmd-compute.service 
    register: csmdcompute_service_result
    ignore_errors: yes

  - debug: 
      msg: csmd-compute.service is NOT running
    when: csmdcompute_service_result.rc != 0  
