###########################################################
#     csmStart.yml
#
#     Copyright IBM Corporation 2020 All Rights Reserved

#     This program is licensed under the terms of the Eclipse Public License
#     v1.0 as published by the Eclipse Foundation and available at
#     http://www.eclipse.org/legal/epl-v10.html
#
#     U.S. Government Users Restricted Rights:  Use, duplication or disclosure
#     restricted by GSA ADP Schedule Contract with IBM Corp.
###########################################################
#  sudo ansible-playbook -i hosts  <this.yml>

- hosts: management launch compute
  tasks:
  any_errors_fatal: true 

- hosts: management
  tasks:
  - name: Skip any csmd-master activation if already running
    command:  /bin/systemctl status csmd-master.service 
    register: csmdmaster_service_result
    ignore_errors: yes

  - name: Skip any ccsmd-aggregator activation if already running
    command:  /bin/systemctl status csmd-aggregator.service 
    register: csmdaggregator_service_result
    ignore_errors: yes
    
  - name: start CSM master
    command: /bin/systemctl start csmd-master.service
    when: csmdmaster_service_result.rc != 0
    any_errors_fatal: true
  
  - name: start CSM aggregator
    command: /bin/systemctl start csmd-aggregator.service
    when: csmdaggregator_service_result.rc != 0
    any_errors_fatal: true
    
- hosts: launch
  tasks:
  - name: Skip any csmd-utility activation if already running
    command:  /bin/systemctl status csmd-utility.service 
    register: csmdutility_service_result
    ignore_errors: yes

  - name: start csmd-utility
    command: /bin/systemctl start csmd-utility.service
    when: csmdutility_service_result.rc != 0 
    any_errors_fatal: true 

- hosts: compute
  tasks:
  - name: Skip any csmd-compute activation if already running
    command:  /bin/systemctl status csmd-compute.service 
    register: csmdcompute_service_result
    ignore_errors: yes

  - name: start CSM compute
    command: /bin/systemctl start csmd-compute.service
    when: csmdcompute_service_result.rc != 0  
    any_errors_fatal: true 

- hosts:  management
  tasks:
  - name: compute nodes for in service--make csv, remove last comma, remove blanks
    shell: tr  '\n' ',' < /etc/ibm/nodelist |sed 's/.$/\n/' |sed 's/ //g'
    register: inservicelist_csv

  - debug:
      msg: "inservicelist_csv stdout={{inservicelist_csv.stdout}}"
  
  - name: mark nodes in CSM as IN_SERVICE
    shell: /opt/ibm/csm/bin/csm_node_attributes_update -n "{{inservicelist_csv.stdout}}" -s IN_SERVICE
    any_errors_fatal: true   